--- #YAML:1.0
name:                   CPAN-Mini-Tested
version:                0.23
abstract:               Create a CPAN mirror using modules with passing test reports
author:
  - Barbie <barbie@cpan.org>
  - Robert Rothenberg <rrwo at cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                       5.006
  base:                       0
  CPAN::Mini:                 0.32
  Cache::Simple::TimedExpiry: 0.22
  DBD::SQLite:                1
  DBI:                        0
  File::Basename:             0
  File::Spec::Functions:      0
  LWP::Simple:                0
  Regexp::Assemble:           0.06
recommends:
  Test::CPAN::Meta:           0
  Test::CPAN::Meta::JSON:     0
  Test::Pod:                  1.00
  Test::Pod::Coverage:        0.08
  Test::Prereq:               0
build_requires:
  IO::File:                   0
  Test::More:                 0.70

provides:
  CPAN::Mini::Tested:
    file: lib/CPAN/Mini/Tested.pm
    version: 0.23
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Mini-Tested
  repository: http://github.com/barbie/cpan-mini-tested

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0

