--- #YAML:1.0
name: CPAN-Mini-Tested
version: 0.20
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: |-
  create a CPAN mirror using modules that have passed tests
license: perl
requires:
  CPAN::Mini: 0.32
  Cache::Simple::TimedExpiry: 0.22
  DBD::SQLite: 1
  DBI: 0
  File::Basename: 0
  File::Spec::Functions: 0
  LWP::Simple: 0
  Regexp::Assemble: 0.06
  base: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
provides:
  CPAN::Mini::Tested:
    file: lib/CPAN/Mini/Tested.pm
    version: 0.20
generated_by: Module::Build version 0.2607
